[build]
  command = "npm run build"
  publish = "dist"
  
[dev]
  # Configura un proxy para redirigir solicitudes API durante el desarrollo local
  # Ajusta la URL al backend según sea necesario
  [[redirects]]
    from = "/api/*"
    to = "https://ciendias-api.onrender.com/api/:splat"
    status = 200
    force = true
    headers = { "Access-Control-Allow-Origin" = "*" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[headers]]
  for = "/*" # you can configure the correct paths here
  [headers.values]
    access-control-allow-origin = "*" # see a list of allowed values here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin