[build]
  command = "npm run build"
  publish = "dist"  # Asegúrate de que este directorio contenga el archivo index.html

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
