[build]
  # Ajusta esto al directorio de construcción correcto
  publish = "dist"
  command = "npm run build"

[dev]
  [[redirects]]
    from = "/api/*"
    to = "https://ciendias-api.onrender.com/api/:splat"
    status = 200
    force = true
    headers = { "Access-Control-Allow-Origin" = "*" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
